//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udi.ecommerceCar.Data.Infrastructure.Data.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcommercedbEntities : DbContext
    {
        public EcommercedbEntities()
            : base("name=EcommercedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DetalleVentaProducto> DetalleVentaProducto { get; set; }
        public virtual DbSet<DetalleVentaServicio> DetalleVentaServicio { get; set; }
        public virtual DbSet<DetalleVentaVehiculo> DetalleVentaVehiculo { get; set; }
        public virtual DbSet<Imagen> Imagen { get; set; }
        public virtual DbSet<InventarioVehiculo> InventarioVehiculo { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TestDrive> TestDrive { get; set; }
        public virtual DbSet<TipoCaja> TipoCaja { get; set; }
        public virtual DbSet<TipoProducto> TipoProducto { get; set; }
        public virtual DbSet<TipoServicio> TipoServicio { get; set; }
        public virtual DbSet<TipoVehiculo> TipoVehiculo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }
        public virtual DbSet<VentaProducto> VentaProducto { get; set; }
        public virtual DbSet<VentaServicio> VentaServicio { get; set; }
        public virtual DbSet<VentaVehiculo> VentaVehiculo { get; set; }
    }
}
