//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udi.ecommerceCar.Data.Infrastructure.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicio()
        {
            this.DetalleVentaServicio = new HashSet<DetalleVentaServicio>();
        }
    
        public int ServicioID { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<bool> Estado { get; set; }
        public int TipoServicioID { get; set; }
        public string UrlAmigable { get; set; }
        public Nullable<bool> VisibleMain { get; set; }
        public Nullable<int> Puntuacion { get; set; }
        public Nullable<int> ImagenID { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionCorta { get; set; }
        public string Nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVentaServicio> DetalleVentaServicio { get; set; }
        public virtual Imagen Imagen { get; set; }
        public virtual TipoServicio TipoServicio { get; set; }
    }
}
