//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Udi.ecommerceCar.Data.Infrastructure.Data.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.InventarioVehiculo = new HashSet<InventarioVehiculo>();
            this.TestDrive = new HashSet<TestDrive>();
        }
    
        public int VehiculoID { get; set; }
        public Nullable<int> CantidadPuertas { get; set; }
        public Nullable<bool> HabilitadoTestDrive { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> TipoVehiculoID { get; set; }
        public Nullable<int> TipoCajaID { get; set; }
        public string NombreModelo { get; set; }
        public int MarcaID { get; set; }
        public string UrlAmigable { get; set; }
        public Nullable<bool> VisibleMain { get; set; }
        public Nullable<int> Puntuacion { get; set; }
        public Nullable<int> ImagenID { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionCorta { get; set; }
    
        public virtual Imagen Imagen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioVehiculo> InventarioVehiculo { get; set; }
        public virtual Marca Marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestDrive> TestDrive { get; set; }
        public virtual TipoCaja TipoCaja { get; set; }
        public virtual TipoVehiculo TipoVehiculo { get; set; }
    }
}
